name: example
description: simple puzzletak neon widget

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  puzzletak_neon_widget:
    path: "../"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  fonts:
    - family: one
      fonts:
        - asset: assets/fonts/1.ttf
    - family: two
      fonts:
        - asset: assets/fonts/2.ttf
    - family: tree
      fonts:
        - asset: assets/fonts/3.ttf
    - family: four
      fonts:
        - asset: assets/fonts/4.ttf
    - family: five
      fonts:
        - asset: assets/fonts/5.ttf