name: text_neon_widget
description: Flutter Neon widget Customize text with neon animations.
version: 1.0.5
homepage: https://github.com/PuzzleTakX
repository: https://github.com/PuzzleTakX/text_neon_widget


environment:
  sdk: '>=2.12.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
