name: text_neon_widget
description: A Neon widget for Flutter With this widget, you can bring all your text to life with neon animations, and all elements are customizable,allowing you to personalize them as you like.
version: 1.0.4
homepage: https://puzzletak.ir
repository: https://github.com/PuzzleTakX/text_neon_widget


environment:
  sdk: '>=2.12.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
